apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "harbor"
spec:
  descriptor:
    links:
      - description: Open App
        # needs to match applicationUrl in kots-app.yaml
        url: "https://harbor"
