---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: harbor
spec:
  groups:
  - name: harbor
    title: Services
    description: Configures the high-level parameters for the services
    items:
    - name: domain
      title: Domain
      help_text: "The base domain for Harbor services"
      type: text
      required: true
      default: "harbor.local"
  - name: tls
    title: TLS
    description: Configures TLS for the exposed services
    items:
    - name: tls-issuer-type
      title: Issuer Type
      help_text: "Type of certificate issuer to use on to issue certificates"
      type: select_one
      items:
      - name: issuer
        title: Issuer
      - name: cluster-issuer
        title: Cluster Issuer
    - name: tls-issuer-name
      title: Issuer Name
      help_text: "Which issuer/cluster issuer should to use to generate certificates"
      type: text
      required: true
